Fix registration request leaks
punica/wakaama pull request #13
Opened 2019-05-03 14:12 UTC by Lycopersicum

2019-05-03 14:25 UTC, GiedriusM submitted a review, later dismissed

2019-05-06 07:15 UTC, taubel requested changes

2019-05-06 07:15 UTC, taubel commented on core/registration.c
> -                // we reset this registration
Why delete the comment?

2019-05-06 09:04 UTC, taubel approved these changes

2019-05-06 14:54 UTC, GiedriusM approved these changes

2019-05-06 15:00 UTC, merged